<?php 

header("Access-Control-Allow-Origin: *");
header('Access-Control-Allow-Methods: GET');
header('Access-Control-Allow-Headers: Content-Type, Authorization');

require('PHPMailer/src/PHPMailer.php');
require('PHPMailer/src/SMTP.php');
require('PHPMailer/src/Exception.php');

function clear_input($input_data)
{
    return htmlspecialchars(stripslashes(trim($input_data)));
}


$response['msg'] = 'Something went wrong while sending email.' ;
$response['status'] = False ;

$allData = $_POST['allData'];
$name = clear_input( $_POST['name'] );
$email = clear_input( $_POST['email' )];

if( empty($allData) || $name || $email)
{
	$response['msg'] = 'Data not found.' ;
	exit( json_encode($response) );
}

$allDataObj = json_decode($allData);

try
{
    $mail = new PHPMailer\PHPMailer\PHPMailer();

    $mail->isSMTP();                                            // Send using SMTP
    $mail->Host       = 'smtp.mailtrap.io';                    // Set the SMTP server to send through
    // $mail->Host       = '172.16.7.57';
    $mail->SMTPAuth   = true;                                   // Enable SMTP authentication
    $mail->Username   = 'b3710ca1faebff';                     // SMTP username
    $mail->Password   = '957cc8bbfa26e1';                               // SMTP password
    // $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;         // Enable TLS encryption;   `PHPMailer::ENCRYPTION_SMTPS` encouraged
    $mail->SMTPSecure = 'tls';
    $mail->Port       = 2525;
    // $mail->Port       = 25; 

    $mail->SetFrom('noreply@example.com', 'example.com'); //Name is optional
    $mail->isHTML(true); 
    $mail->Subject = 'Email Update for ( '. $name .' )';
    $mail->AddAddress( 'to@example.com' );
    $mail->addCC('imranashik50@gmail.com');

    $mail_body = "<h1>Testing mail</h1> <br> <p>This is an autogenerated email. please do not panic.</p>";

    $mail->Body = $mail_body;

    $mail->Send();
    $response['msg'] = 'Thanks! An email has been sent successfully.' ;
    $response['status'] = True ;
}


catch (Exception $e) 
{
    $response['msg'] = "Message could not be sent. Mailer Error: {$mail->ErrorInfo}" ;
    $response['status'] = False ;
}


echo(json_encode($response));

 ?>